# Generated by Django 3.2.7 on 2021-11-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mountpoint',
            name='thruk_host',
        ),
        migrations.AlterField(
            model_name='mountpoint',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Key Host name+svc'),
        ),
    ]
