# Generated by Django 3.2.7 on 2021-09-17 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contragent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Contragent Id')),
                ('name', models.CharField(max_length=255, verbose_name='Contragent Name')),
                ('archived', models.BooleanField(verbose_name='Archived or not')),
                ('archived_datetime', models.DateTimeField(null=True, verbose_name='Archived DateTime')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Customer Id')),
                ('name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('archived', models.BooleanField(verbose_name='Archived or not')),
                ('archived_datetime', models.DateTimeField(null=True, verbose_name='Archived DateTime')),
            ],
        ),
        migrations.CreateModel(
            name='ThrukHost',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Thruk Host Key')),
                ('peer_key', models.CharField(max_length=16, verbose_name='Thruk peer key')),
                ('peer_name', models.CharField(max_length=16, verbose_name='Thruk peer name')),
                ('name', models.CharField(max_length=255, verbose_name='Nagios host name')),
                ('display_name', models.CharField(max_length=255, verbose_name='Nagios host display name')),
                ('alias', models.CharField(max_length=255, verbose_name='Nagios host alias')),
                ('address', models.CharField(max_length=255, verbose_name='Nagios host address')),
                ('host_type', models.CharField(max_length=32, null=True, verbose_name='Nagios _HOST_TYPE')),
                ('clid_source', models.IntegerField(null=True, verbose_name='CLID')),
                ('customer', models.CharField(max_length=255, null=True, verbose_name='Nagios _CUSTOMER')),
                ('support_group', models.CharField(max_length=255, null=True, verbose_name='SD Support Group')),
                ('icon_image_alt', models.CharField(max_length=255, null=True, verbose_name='Responsible Group')),
                ('checks_enabled', models.IntegerField(verbose_name='Is Check enabled')),
                ('check_command', models.CharField(max_length=255, null=True, verbose_name='Check Command')),
                ('process_performance_data', models.IntegerField(verbose_name='Is Performance Data collecting')),
                ('state', models.IntegerField(verbose_name='State Severity')),
                ('state_type', models.IntegerField(verbose_name='State Type')),
                ('acknowledged', models.IntegerField(verbose_name='Is Acknowledged')),
                ('scheduled_downtime_depth', models.IntegerField(null=True, verbose_name='Downtime Depth')),
                ('archived', models.BooleanField(null=True, verbose_name='Archived or not')),
                ('archived_datetime', models.DateTimeField(null=True, verbose_name='Archived DateTime')),
                ('clid_checked', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='explorer.contragent')),
            ],
        ),
        migrations.AddField(
            model_name='contragent',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='explorer.customer'),
        ),
    ]
